### ISSUE TITLE
预训练模型在哪

### ISSUE THREAD

**Issue by 774889315** [bytedance/BEE#1]
“Please download the pretrained models here.”，意思是提供了预训练模型吗，在哪下载？

**Comment by Wubyte** [comment]
Due to the limitation of the storage on github, we provide large files in cloud storage, and here is the link:
Link: https://pan.baidu.com/s/1vW9emHqqHrDZJ1abS4UCxA 
Extra code: dwc0
This info is also updated in readme now.
