### ISSUE TITLE
KeyError: 'gaussian_conditional._quantized_cdf

### ISSUE THREAD

**Issue by DL19970112** [bytedance/BEE#2]
Hello,
After downloading the pretrained models,
run:  "python3 Encoder/CoreEncApp.py -i kodim01.png -o kodim01.bin --ckpt checkpoints/model.ckpt-02 --target_rate 0.06"
error:  "KeyError: 'gaussian_conditional._quantized_cdf'"

Could this be due to compilation problems in Compressai ? How to solve this problem?

**Comment by DL19970112** [comment]
The environment I used is "pytorch1.9.0, python3.8, cuda11.4"
I built compressai1.1.4 in Python3.8 and obtained _cxx.cpython-38-x86_64-linux-gnu. so and ans.cpython-38-x86_64-linux-gnu.so, And replace these two files in the BEE-main /Common folder. The ”KeyError: 'gaussian_conditional._quantized_cdf” is still there.

**Comment by Wubyte** [comment]
Thanks for your bug reporting! This issue is caused by the encrypted decoder, we already fixed it in the latest version [v1.0.1.](https://github.com/bytedance/BEE/releases/tag/v1.0.1) Pls download the latest code version and checkpoint version to fix this issue.
